on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.

    - uses: aarnott/nbgv@v0.3
      with:
        setAllVars: true

    - run: echo "NBGV_SemVer2 $NBGV_SemVer2"
      shell: bash

    - run: npm pack npx/xplat/

    - run: npm pack npx/win-x64/

    - run: npm pack npx/osx-x64/
      
    - run: npm pack npx/linux-x64/
